version: "3"

services:

  frontend:
    build: ./cinema_react
    volumes:
      - ./cinema_react/:/app/
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL

  mydb:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - 5432

  server:
    build: ./fastapi_cinema
    volumes:
      - ./fastapi_cinema/:/var/www/server/
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER
      - host
      - port
      - secret_key
      - algorithm
      - access_token_expire_minutes
      - REDIS_HOST
    command: uvicorn main:app --reload --host 0.0.0.0
    depends_on:
      - mydb
      - redis_broker

  redis_broker:
    image: redis/redis-stack
    ports:
      - "6379:6379"
